name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy on PythonAnywhere
        run: |
          curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/MikaelReis.pythonanywhere.com/reload/ \
            -H 'Authorization: Token ${{ secrets.PA_API_TOKEN }}'
